# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q pipenv codecov
        pipenv sync --dev
    - name: Run safety check from pyup.io
      run: |
        pipenv run safety check
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --max-line-length=127 --statistics
    - name: Run tests with pytest
      run: |
        pipenv run pytest libpythonpro_fr --cov=libpythonpro_fr --cov-report=xml
    - name: Run code coverage with codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false # optional (default = false)
        token: ${{ secrets.token }}
        verbose: false # optional (default = false)
